import { ProductModel } from '../models/product.model';

export const MOCK_PRODUCTS: ProductModel[] = [
  {
    id: "prod-1",
    name: "Exquisite Woolen Knit Cardigan",
    description: "Handcrafted with premium merino wool, this chunky knit cardigan offers unparalleled warmth.",
    longDescription: "Intricately hand-coiled and knitted using 100% organic merino wool fibers. Features custom horn buttons, drop shoulders, and a heavy rib-knit trim. Hand-spun in our local textile studios to guarantee a soft, non-scratch touch that lasts a lifetime.",
    price: 189.00,
    originalPrice: 240.00,
    discount: 21,
    category: "Apparel",
    subCategory: "Cardigans",
    images: [
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=600",
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=600",
    tags: ["Apparel", "Merino", "Knitwear", "Winter"],
    inStock: true,
    stockQuantity: 12,
    materials: ["100% Merino Wool"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Charcoal", "Cream", "Oatmeal"],
    rating: 4.8,
    reviewCount: 34,
    isFeatured: true,
    isNew: true,
    createdAt: new Date("2026-01-15T00:00:00.000Z")
  },
  {
    id: "prod-2",
    name: "Organic Linen Summer Throw",
    description: "Woven from organic linen fibers, this lightweight throw adds a rustic yet refined texture.",
    longDescription: "Crafted from flax harvested organically in Belgium. Stonewashed for ultimate softness and finished with a hand-fringed hem. The perfect light layer for summer evenings or decor accents.",
    price: 125.00,
    originalPrice: 125.00,
    discount: 0,
    category: "Home Decor",
    subCategory: "Throws",
    images: [
      "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600",
      "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600",
    tags: ["Home Decor", "Linen", "Summer", "Throw"],
    inStock: true,
    stockQuantity: 8,
    materials: ["100% Belgian Linen"],
    sizes: ["Standard (50\"x70\")"],
    colors: ["Soft Cream", "Sage", "Terracotta"],
    rating: 4.9,
    reviewCount: 21,
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2026-02-10T00:00:00.000Z")
  },
  {
    id: "prod-3",
    name: "Artisan Macramé Tapestry",
    description: "Intricate macramé wall hanging featuring beautiful geometric thread patterns.",
    longDescription: "A stunning visual centerpiece for high-end bedrooms and lounges. Lovingly knotted by hand using unbleached organic cotton cords suspended from a natural driftwood branch.",
    price: 95.00,
    originalPrice: 120.00,
    discount: 20,
    category: "Home Decor",
    subCategory: "Tapestries",
    images: [
      "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?q=80&w=600",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?q=80&w=600",
    tags: ["Home Decor", "Cotton", "Artisan", "Macrame"],
    inStock: true,
    stockQuantity: 5,
    materials: ["Organic Cotton Rope", "Driftwood"],
    sizes: ["Medium (3ft x 4ft)"],
    colors: ["Natural Ivory"],
    rating: 4.7,
    reviewCount: 15,
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2026-03-05T00:00:00.000Z")
  },
  {
    id: "prod-4",
    name: "Twisted Cotton Scarf",
    description: "Elegant unisex scarf featuring beautifully twisted cotton threads and double-stitched borders.",
    longDescription: "Lightweight, breathable, and exceptionally soft. Hand-finished with delicate tassels, this signature twisted pattern scarf adds a touch of artisan charm to any outfit.",
    price: 58.00,
    originalPrice: 58.00,
    discount: 0,
    category: "Accessories",
    subCategory: "Scarves",
    images: [
      "https://images.unsplash.com/photo-1577903048559-fb487b2743df?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1577903048559-fb487b2743df?q=80&w=600",
    tags: ["Accessories", "Cotton", "Scarf", "Spring"],
    inStock: true,
    stockQuantity: 20,
    materials: ["100% GOTS Cotton"],
    sizes: ["One Size"],
    colors: ["Indigo Blue", "Charcoal", "Soft Cream"],
    rating: 4.6,
    reviewCount: 18,
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2026-04-01T00:00:00.000Z")
  },
  {
    id: "prod-5",
    name: "Luxe Woven Cashmere Blanket",
    description: "Indulge in absolute luxury with this ultra-soft dual-colored cashmere blanket.",
    longDescription: "Sourced from high-altitude Mongolian cashmere fibers. Extremely lightweight yet offers superior warmth and insulation. Features a reversible dual-colored knit showcasing our signature twisted stitch.",
    price: 350.00,
    originalPrice: 450.00,
    discount: 22,
    category: "Home Decor",
    subCategory: "Blankets",
    images: [
      "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=600",
    tags: ["Home Decor", "Cashmere", "Premium", "Blanket"],
    inStock: true,
    stockQuantity: 4,
    materials: ["100% Mongolian Cashmere"],
    sizes: ["Queen (90\"x90\")"],
    colors: ["Rich Purple & Oatmeal", "Charcoal & Grey"],
    rating: 5.0,
    reviewCount: 9,
    isFeatured: true,
    isNew: true,
    createdAt: new Date("2026-04-18T00:00:00.000Z")
  },
  {
    id: "prod-6",
    name: "Woven Cotton Storage Basket",
    description: "Minimalist and functional storage basket tightly hand-coiled with reinforced rope.",
    longDescription: "A heavy-duty storage solution that complements minimalist Scandinavian interiors. Features double stitched leather handles and a flat bottom. Keeps shape easily.",
    price: 42.00,
    originalPrice: 42.00,
    discount: 0,
    category: "Home Decor",
    subCategory: "Baskets",
    images: [
      "https://images.unsplash.com/photo-1531835551805-16d864c8d311?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1531835551805-16d864c8d311?q=80&w=600",
    tags: ["Home Decor", "Cotton", "Scandinavian", "Basket"],
    inStock: true,
    stockQuantity: 15,
    materials: ["Cotton Rope", "Full-grain Leather handles"],
    sizes: ["Medium", "Large"],
    colors: ["White & Cream", "White & Charcoal"],
    rating: 4.5,
    reviewCount: 11,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-12T00:00:00.000Z")
  },
  {
    id: "prod-7",
    name: "Deep Rose Gold Eternity Ring",
    "description": "A stunning solid 18k rose gold ring paved with ethically sourced micro-diamonds.",
    longDescription: "Intended to be stacked or worn as a subtle statement of elegance. Handcrafted with deep 18k rose gold matching our signature primary brand tone. Every micro-diamond is carefully calibrated and hand-paved.",
    price: 480.00,
    originalPrice: 599.00,
    discount: 20,
    category: "Jewelry",
    subCategory: "Rings",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600",
      "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600",
    tags: ["Jewelry", "Rose Gold", "Diamond", "Ring"],
    inStock: true,
    stockQuantity: 6,
    materials: ["18k Rose Gold", "0.45ct Diamonds"],
    sizes: ["6", "7", "8"],
    colors: ["Rose Gold"],
    rating: 4.9,
    reviewCount: 12,
    isFeatured: true,
    isNew: true,
    createdAt: new Date("2026-05-01T00:00:00.000Z")
  },
  {
    id: "prod-8",
    name: "Elegant Gold Pendant Necklace",
    "description": "An exquisite solid 24k gold coin pendant hanging from a delicate matching cable chain.",
    longDescription: "Inspired by classical Greek motifs. The textured coin pendant features hand-carved details that reflect light with vintage elegance. Accompanied by a adjustable 18-inch lobster claw chain.",
    price: 620.00,
    originalPrice: 620.00,
    discount: 0,
    category: "Jewelry",
    subCategory: "Necklaces",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600",
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600",
    tags: ["Jewelry", "24k Gold", "Pendant", "Necklace"],
    inStock: true,
    stockQuantity: 3,
    materials: ["24k Yellow Gold"],
    sizes: ["18\" Chain"],
    colors: ["Elegant Gold"],
    rating: 4.8,
    reviewCount: 8,
    isFeatured: true,
    isNew: false,
    createdAt: new Date("2026-05-10T00:00:00.000Z")
  },
  {
    id: "prod-9",
    name: "Rich Amethyst Thread Bracelet",
    "description": "Premium hand-twisted purple silk threads accented by raw amethyst crystals and gold beads.",
    longDescription: "Incorporates our brand's rich purple tones. The silk threads are hand-braided utilizing an ancient Japanese weaving technique and secured by an adjustable gold slide connector.",
    price: 140.00,
    originalPrice: 180.00,
    discount: 22,
    category: "Jewelry",
    subCategory: "Bracelets",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=600",
    tags: ["Jewelry", "Amethyst", "Silk", "Bracelet"],
    inStock: true,
    stockQuantity: 10,
    materials: ["Raw Amethyst", "Natural Silk threads", "14k Gold beads"],
    sizes: ["Adjustable"],
    colors: ["Rich Purple & Gold"],
    rating: 4.7,
    reviewCount: 16,
    isFeatured: false,
    isNew: true,
    createdAt: new Date("2026-05-15T00:00:00.000Z")
  },
  {
    id: "prod-10",
    name: "Art Deco Pearl Drop Earrings",
    "description": "Sleek baroque pearls hanging gracefully from geometric gold mounts set with emerald crystals.",
    longDescription: "A sophisticated fusion of organic baroque pearl shapes and structural Art Deco geometry. Made in hypoallergenic brass layered in 18k yellow gold. No two pairs are identical.",
    price: 260.00,
    originalPrice: 260.00,
    discount: 0,
    category: "Jewelry",
    subCategory: "Earrings",
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600",
    tags: ["Jewelry", "Pearl", "Drop Earrings", "Vintage"],
    inStock: true,
    stockQuantity: 5,
    materials: ["Baroque Pearls", "18k Gold plated Brass", "Emerald Cubic Zirconia"],
    sizes: ["2\" Drop"],
    colors: ["Pearl White & Gold"],
    rating: 4.9,
    reviewCount: 19,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-18T00:00:00.000Z")
  },
  {
    id: "prod-11",
    name: "Chunky Gold Link Bracelet",
    "description": "Bold interconnected chain link bracelet finished in brushed 18k yellow gold plating.",
    longDescription: "Designed to stand out with modern minimal silhouettes. The links are solid, hand-buffed, and finished with a unique double security box clasp. Feels substantial yet comfortable.",
    price: 310.00,
    originalPrice: 399.00,
    discount: 22,
    category: "Jewelry",
    subCategory: "Bracelets",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=600",
    tags: ["Jewelry", "Gold Plated", "Link", "Bracelet"],
    inStock: true,
    stockQuantity: 7,
    materials: ["18k Gold Plated Sterling Silver"],
    sizes: ["7.5\" Length"],
    colors: ["Elegant Gold"],
    rating: 4.6,
    reviewCount: 14,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-20T00:00:00.000Z")
  },
  {
    id: "prod-12",
    name: "Luxury Woven Wool Coat",
    "description": "Tailored double-breasted coat crafted from premium twisted wool threads.",
    longDescription: "A masterwork of cold-weather tailoring. Built from dense, wind-resistant wool woven into a herringbone structure. Fully lined in organic silk for effortless layering comfort.",
    price: 420.00,
    originalPrice: 420.00,
    discount: 0,
    category: "Apparel",
    subCategory: "Coats",
    images: [
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=600",
    tags: ["Apparel", "Wool", "Coat", "Herringbone"],
    inStock: true,
    stockQuantity: 4,
    materials: ["85% Virgin Wool", "15% Silk lining"],
    sizes: ["M", "L", "XL"],
    colors: ["Charcoal Black", "Camel Brown"],
    rating: 5.0,
    reviewCount: 7,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-22T00:00:00.000Z")
  },
  {
    id: "prod-13",
    name: "Minimalist Rose Gold Hoop Earrings",
    "description": "Thin, lightweight hoop earrings crafted in solid 14k rose gold with mirror polish.",
    longDescription: "Timeless, basic, and essential. Extremely lightweight hoops designed for comfortable multi-piercing arrangements. Features a seamless click-in clasp mechanism.",
    price: 190.00,
    originalPrice: 220.00,
    discount: 13,
    category: "Jewelry",
    subCategory: "Earrings",
    images: [
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600",
    tags: ["Jewelry", "Rose Gold", "Hoops", "Minimalist"],
    inStock: true,
    stockQuantity: 18,
    materials: ["14k Rose Gold"],
    sizes: ["30mm Diameter"],
    colors: ["Rose Gold"],
    rating: 4.7,
    reviewCount: 26,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-24T00:00:00.000Z")
  },
  {
    id: "prod-14",
    name: "Gold Thread Linen Tablecloth",
    "description": "Stunning dining tablecloth woven with belgian linen and fine metallic gold thread borders.",
    longDescription: "Upgrade your formal dinners with this premium, heavy-weight linen tablecloth. Finished with a gold-threaded double mitered hem for vintage luxury accents.",
    price: 110.00,
    originalPrice: 110.00,
    discount: 0,
    category: "Home Decor",
    subCategory: "Tablecloths",
    images: [
      "https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1606722590583-6951b5ea92ad?q=80&w=600",
    tags: ["Home Decor", "Linen", "Gold Thread", "Tablecloth"],
    inStock: true,
    stockQuantity: 10,
    materials: ["90% Linen", "10% Lurex Gold fibers"],
    sizes: ["60\" x 120\""],
    colors: ["Cream & Gold"],
    rating: 4.8,
    reviewCount: 13,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-25T00:00:00.000Z")
  },
  {
    id: "prod-15",
    name: "Classic Cable Knit Crewneck",
    "description": "Mid-weight cotton crewneck sweater featuring dense classic cable knitting.",
    longDescription: "A comfortable mid-layer for autumn and spring transitions. Cable knit details across chest and arms, knitted using pre-shrunk organic GOTS cotton yarn.",
    price: 135.00,
    originalPrice: 160.00,
    discount: 15,
    category: "Apparel",
    subCategory: "Sweaters",
    images: [
      "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=600",
    tags: ["Apparel", "Cotton", "Cable Knit", "Crewneck"],
    inStock: true,
    stockQuantity: 11,
    materials: ["100% GOTS Organic Cotton"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory", "Soft Beige", "Slate Blue"],
    rating: 4.6,
    reviewCount: 20,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-26T00:00:00.000Z")
  },
  {
    id: "prod-16",
    name: "Fine Diamond Solitaire Necklace",
    "description": "An exquisite round brilliant-cut 0.50ct solitaire diamond resting on an 18k white gold chain.",
    longDescription: "Understated luxury at its finest. The round brilliant-cut diamond is secured in a secure 4-prong claw mounting to allow light to penetrate from all facets. Conflict-free and certified.",
    price: 950.00,
    originalPrice: 1200.00,
    discount: 20,
    category: "Jewelry",
    subCategory: "Necklaces",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600",
    tags: ["Jewelry", "Diamond", "Solitaire", "White Gold"],
    inStock: true,
    stockQuantity: 2,
    materials: ["18k White Gold", "0.50ct Diamond (VVS1, F)"],
    sizes: ["16\" Chain"],
    colors: ["White Gold"],
    rating: 5.0,
    reviewCount: 6,
    isFeatured: true,
    isNew: true,
    createdAt: new Date("2026-05-27T00:00:00.000Z")
  },
  {
    id: "prod-17",
    name: "Raw Linen Bed Runner",
    "description": "Rustic heavyweight pure linen runner woven with accent borders and thick edges.",
    longDescription: "Adds tactile interest and geometric contrast to solid duvets. Woven from coarse flax yarn which creates a lovely irregular thick texture.",
    price: 85.00,
    originalPrice: 85.00,
    discount: 0,
    category: "Home Decor",
    subCategory: "Bedding",
    images: [
      "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=600",
    tags: ["Home Decor", "Linen", "Bed Runner", "Rustic"],
    inStock: true,
    stockQuantity: 14,
    materials: ["100% Belgian Flax Linen"],
    sizes: ["Queen (24\"x90\")", "King (24\"x105\")"],
    colors: ["Natural Flax", "Oatmeal", "Sage"],
    rating: 4.5,
    reviewCount: 15,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-28T00:00:00.000Z")
  },
  {
    id: "prod-18",
    name: "Luxury Silk Eyemask & Pillowcase Set",
    "description": "Premium mulberry silk sleep set designed for skin care and absolute comfort.",
    longDescription: "Made from GOTS-certified 22 Momme organic mulberry silk. Helps preserve skin hydration and prevents hair frizzing. Packaged in a beautiful brand embossed gift box.",
    price: 95.00,
    originalPrice: 115.00,
    discount: 17,
    category: "Accessories",
    subCategory: "Sets",
    images: [
      "https://images.unsplash.com/photo-1577903048559-fb487b2743df?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1577903048559-fb487b2743df?q=80&w=600",
    tags: ["Accessories", "Silk", "Pillowcase", "Gift Set"],
    inStock: true,
    stockQuantity: 9,
    materials: ["100% 22 Momme Mulberry Silk"],
    sizes: ["Standard Queen Size"],
    colors: ["Pearl White", "Blush Pink", "Rich Charcoal"],
    rating: 4.8,
    reviewCount: 30,
    isFeatured: false,
    isNew: true,
    createdAt: new Date("2026-05-29T00:00:00.000Z")
  },
  {
    id: "prod-19",
    name: "Minimalist Gold Band Ring",
    "description": "Elegant solid 18k yellow gold band ring, hand-sculpted with soft irregular contours.",
    longDescription: "A subtle, organic twist on the classic gold wedding band. Features hand-carved undulations and a matte finish for a contemporary raw luxury aesthetic.",
    price: 280.00,
    originalPrice: 280.00,
    discount: 0,
    category: "Jewelry",
    subCategory: "Rings",
    images: [
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600",
    tags: ["Jewelry", "18k Gold", "Band", "Ring"],
    inStock: true,
    stockQuantity: 10,
    materials: ["18k Yellow Gold"],
    sizes: ["6", "7", "8", "9"],
    colors: ["Elegant Gold"],
    rating: 4.9,
    reviewCount: 18,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-30T00:00:00.000Z")
  },
  {
    id: "prod-20",
    name: "Luxury Linen Lounge Robe",
    "description": "Breathable, lightweight linen kimono robe finished with French seams and a sash belt.",
    longDescription: "A loungewear icon. Pre-washed for supreme softness and drape. Features pockets and an adjustable waist belt. Made in Lithuania.",
    price: 145.00,
    originalPrice: 180.00,
    discount: 19,
    category: "Apparel",
    subCategory: "Loungewear",
    images: [
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=600"
    ],
    mainImage: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?q=80&w=600",
    tags: ["Apparel", "Linen", "Loungewear", "Robe"],
    inStock: false,
    stockQuantity: 0,
    materials: ["100% Lithuanian Flax Linen"],
    sizes: ["S/M", "L/XL"],
    colors: ["Natural Flax", "Pearl White", "Terracotta"],
    rating: 4.7,
    reviewCount: 22,
    isFeatured: false,
    isNew: false,
    createdAt: new Date("2026-05-31T00:00:00.000Z")
  }
];
